# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
author: Nigel Ng
title:            BLOG
tagline:          "Nigel Ng"
description:      "standup comedy and other nonsense"
url:              http://blog.nigelngcomedy.com
baseurl:          ''
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

# for seo
twitter:
    username: MrNigelNg

social:
  links:
    - https://twitter.com/MrNigelNg
    - https://www.instagram.com/mrnigelng/
    - https://www.facebook.com/nigelngcomedy

paginate:         2
paginate_path:    "/page:num/"

version:          2.1.0

plugins:
  - jekyll-seo-tag

kramdown:
  input: GFM
  hard_wrap: false
