# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            BLOG
tagline:          "nigel's comedy ramblings"
description:      "nigel's comedy ramblings"
url:              http://blog.nigelngcomedy.com
baseurl:          ''
# Travis will install Bundler dependencies in ./vendor, so we need to exclude it
# otherwise Jekyll will try to build it (and fail)
exclude:          [vendor]

author:
  name:           'Nigel Ng'
  url:            http://nigelngcomedy.com
  twitter:  MrNigelNg

paginate:         3
paginate_path:    "/page:num/"

# Custom vars
version:          2.1.0

#github:
    #repo:         https://github.com/algolia/algoliasearch-jekyll-hyde

gems:
  - jekyll-seo-tag

kramdown:
  input: GFM
  hard_wrap: false
